Add default packages to attributes
packages was missing a default attribute, this resulted in the following error when running chefspec testing locally on ubuntu:

```
NoMethodError:
       undefined method `each' for nil:NilClass
     # /tmp/d20151013-20375-1tqy8ps/cookbooks/htpasswd/recipes/packages.rb:1:in `from_file'
     # /tmp/d20151013-20375-1tqy8ps/cookbooks/htpasswd/recipes/default.rb:21:in `from_file'
```